/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BJ;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Julian
 */
public class MeinSpiel extends javax.swing.JFrame {

    /**
     * Creates new form MeinSpiel
     */
    private ArrayList<JLabel> lblSpielerKarten;
    private BlackjackSpiel hintergrundspiel;
    protected int count;
    
    public MeinSpiel() {
        initComponents();
        lblSpielerKarten = new ArrayList<>();
        lblSpielerKarten.add(lblSpielerKarte1);
        lblSpielerKarten.add(lblSpielerKarte2);
        lblSpielerKarten.add(lblSpielerKarte3);
        lblSpielerKarten.add(lblSpielerKarte4);
        lblSpielerKarten.add(lblSpielerKarte5);
        hintergrundspiel = new BlackjackSpiel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnHold = new javax.swing.JButton();
        btnNeueKarte = new javax.swing.JButton();
        btnNeueRunde = new javax.swing.JButton();
        lblSpielerKarte1 = new javax.swing.JLabel();
        lblSpielerKarte2 = new javax.swing.JLabel();
        lblSpielerKarte3 = new javax.swing.JLabel();
        lblSpielerKarte4 = new javax.swing.JLabel();
        lblSpielerKarte5 = new javax.swing.JLabel();
        lblSpielerKarte6 = new javax.swing.JLabel();
        lblSpielerKarte7 = new javax.swing.JLabel();
        lblSpielerKarte8 = new javax.swing.JLabel();
        lblSpielerKarte9 = new javax.swing.JLabel();
        lblSpielerKarte10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Spieler");

        jLabel2.setText("Dealer");

        btnHold.setText("Hold");
        btnHold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoldActionPerformed(evt);
            }
        });

        btnNeueKarte.setText("Neue Karte");
        btnNeueKarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNeueKarteActionPerformed(evt);
            }
        });

        btnNeueRunde.setText("Neue Runde");
        btnNeueRunde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNeueRundeActionPerformed(evt);
            }
        });

        lblSpielerKarte1.setMaximumSize(new java.awt.Dimension(59, 91));
        lblSpielerKarte1.setMinimumSize(new java.awt.Dimension(59, 91));
        lblSpielerKarte1.setPreferredSize(new java.awt.Dimension(59, 91));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHold)
                            .addComponent(btnNeueKarte)
                            .addComponent(btnNeueRunde))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblSpielerKarte1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSpielerKarte2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSpielerKarte3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSpielerKarte4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSpielerKarte5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                        .addComponent(lblSpielerKarte10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSpielerKarte9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSpielerKarte8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSpielerKarte7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSpielerKarte6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(285, 285, 285))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSpielerKarte5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSpielerKarte1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSpielerKarte2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSpielerKarte3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSpielerKarte4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSpielerKarte6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSpielerKarte10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSpielerKarte9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSpielerKarte8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSpielerKarte7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(120, 120, 120)
                .addComponent(btnNeueKarte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHold)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNeueRunde)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoldActionPerformed
        // TODO add your handling code here:
        System.out.println("BJ.MeinSpiel.btnHoldActionPerformed()");
    }//GEN-LAST:event_btnHoldActionPerformed

    private void btnNeueRundeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNeueRundeActionPerformed
        // TODO add your handling code here:
        System.out.println("BJ.MeinSpiel.btnNeueRundeActionPerformed()");
    }//GEN-LAST:event_btnNeueRundeActionPerformed

    private void btnNeueKarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNeueKarteActionPerformed
        // TODO add your handling code here:
        //System.out.println("BJ.MeinSpiel.btnNeueKarteActionPerformed()");
        
        hintergrundspiel.getDealer().gibKarte(hintergrundspiel.getSpieler());
        
        //lblSpielerKarte1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Karten/" + hintergrundspiel.getSpieler().getKartenInDerHand().get(0).toString() + ".jpg"))); // NOI18N
        
        String pfad = this.getClass().getClassLoader().getResource("Karten/" + hintergrundspiel.getSpieler().getKartenInDerHand().get(count).toString() + ".jpg").getFile();
        lblSpielerKarten.get(count).setIcon(new ImageIcon(pfad));
        count++;
        //JOptionPane.showMessageDialog(null, hintergrundspiel.getSpieler().toString());     
    }//GEN-LAST:event_btnNeueKarteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeinSpiel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeinSpiel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeinSpiel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeinSpiel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeinSpiel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHold;
    private javax.swing.JButton btnNeueKarte;
    private javax.swing.JButton btnNeueRunde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblSpielerKarte1;
    private javax.swing.JLabel lblSpielerKarte10;
    private javax.swing.JLabel lblSpielerKarte2;
    private javax.swing.JLabel lblSpielerKarte3;
    private javax.swing.JLabel lblSpielerKarte4;
    private javax.swing.JLabel lblSpielerKarte5;
    private javax.swing.JLabel lblSpielerKarte6;
    private javax.swing.JLabel lblSpielerKarte7;
    private javax.swing.JLabel lblSpielerKarte8;
    private javax.swing.JLabel lblSpielerKarte9;
    // End of variables declaration//GEN-END:variables
}
