/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BJ;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Julian
 */
public class SpielMain extends javax.swing.JFrame {

    /**
     * Creates new form SpielMain
     */
    
    private ArrayList<JLabel> lblSpielerKarten;
    private ArrayList<JLabel> lblDealerKarten;
    private BlackjackSpiel hintergrundspiel = new BlackjackSpiel();
    protected int count = 0;
    private Spieler spieler ;
    private Dealer dealer;
    private int SpielerWins1 =0;
    private int DealerWins1 =0;
    
    public SpielMain() {
        
        
        initComponents();
        lblSpielerKarten = new ArrayList<>();
        lblSpielerKarten.add(lblSpielerKarte1);
        lblSpielerKarten.add(lblSpielerKarte2);
        lblSpielerKarten.add(lblSpielerKarte3);
        lblSpielerKarten.add(lblSpielerKarte4);
        lblSpielerKarten.add(lblSpielerKarte5);
        
        lblDealerKarten = new ArrayList<>();
        lblDealerKarten.add(lblDealerKarten1);
        lblDealerKarten.add(lblDealerKarten2);
        lblDealerKarten.add(lblDealerKarten3);
        lblDealerKarten.add(lblDealerKarten4);
        lblDealerKarten.add(lblDealerKarten5);
        
        hintergrundspiel = new BlackjackSpiel();
        spieler = hintergrundspiel.getSpieler();
        dealer = hintergrundspiel.getDealer();
        
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnHold = new javax.swing.JButton();
        btnNeueKarte = new javax.swing.JButton();
        btnNeueRunde = new javax.swing.JButton();
        lblSpielerKarte1 = new javax.swing.JLabel();
        lblSpielerKarte2 = new javax.swing.JLabel();
        lblSpielerKarte3 = new javax.swing.JLabel();
        lblSpielerKarte4 = new javax.swing.JLabel();
        lblSpielerKarte5 = new javax.swing.JLabel();
        lblDealerKarten5 = new javax.swing.JLabel();
        lblDealerKarten4 = new javax.swing.JLabel();
        lblDealerKarten3 = new javax.swing.JLabel();
        lblDealerKarten2 = new javax.swing.JLabel();
        lblDealerKarten1 = new javax.swing.JLabel();
        DealerPunkte = new javax.swing.JLabel();
        SpielerPunkte = new javax.swing.JLabel();
        Gewinner = new javax.swing.JLabel();
        SpielerWins = new javax.swing.JLabel();
        DealerWins = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Spieler");

        jLabel2.setText("Dealer");

        btnHold.setText("Hold");
        btnHold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoldActionPerformed(evt);
            }
        });

        btnNeueKarte.setText("Neue Karte");
        btnNeueKarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNeueKarteActionPerformed(evt);
            }
        });

        btnNeueRunde.setText("Neue Runde");
        btnNeueRunde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNeueRundeActionPerformed(evt);
            }
        });

        lblSpielerKarte1.setMaximumSize(new java.awt.Dimension(59, 91));
        lblSpielerKarte1.setMinimumSize(new java.awt.Dimension(59, 91));
        lblSpielerKarte1.setPreferredSize(new java.awt.Dimension(59, 91));

        DealerPunkte.setText("Dealer Punkte:");

        SpielerPunkte.setText("Spieler Punkte:");

        SpielerWins.setText("SpielerWins:");

        DealerWins.setText("DealerWins:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(285, 285, 285))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHold)
                                    .addComponent(btnNeueKarte)
                                    .addComponent(btnNeueRunde))
                                .addGap(555, 555, 555)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SpielerPunkte, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                    .addComponent(DealerPunkte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Gewinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSpielerKarte1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSpielerKarte2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSpielerKarte3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSpielerKarte4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSpielerKarte5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDealerKarten1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDealerKarten2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDealerKarten3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDealerKarten4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDealerKarten5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SpielerWins)
                            .addComponent(DealerWins))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSpielerKarte5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSpielerKarte2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSpielerKarte3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSpielerKarte1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSpielerKarte4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDealerKarten5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDealerKarten2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDealerKarten3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDealerKarten1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDealerKarten4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNeueKarte)
                    .addComponent(Gewinner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHold)
                    .addComponent(SpielerPunkte)
                    .addComponent(SpielerWins))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNeueRunde)
                    .addComponent(DealerPunkte)
                    .addComponent(DealerWins))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoldActionPerformed
        // TODO add your handling code here:
        btnHold.setEnabled(false);
        btnNeueKarte.setEnabled(false);
        System.out.println("BJ.MeinSpiel.btnHoldActionPerformed()");
        hintergrundspiel.dealerAmZug();
        for (int i = 0; i < dealer.getKartenInDerHand().size(); i++) {
           
            lblDealerKarten.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/Karten/" + dealer.getKartenInDerHand().get(i).toString() + ".jpg")));
            SpielerPunkte.setText("Spieler Punkte: "+spieler.zählePunkte());
            DealerPunkte.setText("Dealer Punkte: "+dealer.zählePunkte()); 
        }
        String gewinner = "";
        if (spieler.zählePunkte() > 21) {
            
            gewinner = "Dealer";
            DealerWins1++;
        }else if (dealer.zählePunkte() > 21) { 
            
            gewinner = "Spieler";
            SpielerWins1++;
        }else if (spieler.zählePunkte() > dealer.zählePunkte()) {
            
            gewinner = "Spieler";
            SpielerWins1++;
        }
        else if (spieler.zählePunkte() < dealer.zählePunkte()) {
            
            gewinner = "Dealer";
            DealerWins1++;
        }
        else if (spieler.zählePunkte() == dealer.zählePunkte()) {
            
            gewinner = "Unentschieden";
        }
        Gewinner.setText("Gewinner: "+gewinner);
        SpielerWins.setText("SpielerWins: "+SpielerWins1);
        DealerWins.setText("DealerWins: "+DealerWins1);
        
    }//GEN-LAST:event_btnHoldActionPerformed

    private void btnNeueRundeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNeueRundeActionPerformed
        btnHold.setEnabled(true);
        btnNeueKarte.setEnabled(true);
        spieler.entferneAlleKarten();
        dealer.entferneAlleKarten();
        for (int i = 0; i < 5; i++) {
            
            lblSpielerKarten.get(i).setIcon(null);
            lblDealerKarten.get(i).setIcon(null);
        }
        SpielerPunkte.setText("Spieler Punkte: 0");
        DealerPunkte.setText("Dealer Punkte: 0");
        String a = "";
        Gewinner.setText("Gewinner: "+a);
    }//GEN-LAST:event_btnNeueRundeActionPerformed

    private void btnNeueKarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNeueKarteActionPerformed
       
        dealer.gibKarte(spieler);
        int current_size= spieler.getKartenInDerHand().size()-1;
        lblSpielerKarten.get(current_size).setIcon(new javax.swing.ImageIcon(getClass().getResource("/Karten/" + spieler.getKartenInDerHand().get(current_size).toString() + ".jpg")));
        SpielerPunkte.setText("Spieler Punkte: "+spieler.zählePunkte());
        DealerPunkte.setText("Dealer Punkte: "+dealer.zählePunkte());
        if (spieler.zählePunkte() >= 21) {
            
            btnHold.setEnabled(false);
            btnNeueKarte.setEnabled(false);
            btnHoldActionPerformed(evt);
        }
        if (spieler.getKartenInDerHand().size() == 5) {
            
            btnHold.setEnabled(false);
            btnNeueKarte.setEnabled(false);
            btnHoldActionPerformed(evt);
        }
    }//GEN-LAST:event_btnNeueKarteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpielMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpielMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpielMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpielMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpielMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DealerPunkte;
    private javax.swing.JLabel DealerWins;
    private javax.swing.JLabel Gewinner;
    private javax.swing.JLabel SpielerPunkte;
    private javax.swing.JLabel SpielerWins;
    private javax.swing.JButton btnHold;
    private javax.swing.JButton btnNeueKarte;
    private javax.swing.JButton btnNeueRunde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDealerKarten1;
    private javax.swing.JLabel lblDealerKarten2;
    private javax.swing.JLabel lblDealerKarten3;
    private javax.swing.JLabel lblDealerKarten4;
    private javax.swing.JLabel lblDealerKarten5;
    private javax.swing.JLabel lblSpielerKarte1;
    private javax.swing.JLabel lblSpielerKarte2;
    private javax.swing.JLabel lblSpielerKarte3;
    private javax.swing.JLabel lblSpielerKarte4;
    private javax.swing.JLabel lblSpielerKarte5;
    // End of variables declaration//GEN-END:variables
}
